export const userType ={
    EMAIL_SIGN_IN_START : 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS:'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE:'EMAIL_SIGN_IN_FAILURE',

    LOGIN_BOX : 'LOGIN_BOX',
    ADD_USER_TO_DATABASE: 'ADD_USER_TO_DATABASE',
    SIGNOUT:'SIGNOUT',


    CONTROL_PANEL : 'CONTROL_PANEL'
}